# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Picture Hunt' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Picture Hunt

  target 'Picture HuntTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Picture HuntUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
